# Generated by Django 4.2.3 on 2024-12-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0007_tagcategory_customtag_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="resources.customtag",
            ),
        ),
    ]
