# Generated by Django 4.2.3 on 2024-12-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_alter_resourcetag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="howto",
            name="selected_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="howto_resources",
                to="resources.tagcategory",
                verbose_name="Category",
            ),
        ),
    ]
