# Generated by Django 4.2.3 on 2024-12-18 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0009_howto_selected_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="assets",
        ),
    ]
